### ISSUE TITLE
thanks for sharing the code, does it work on GAN or mnist? : )

### ISSUE THREAD

**Issue by aflyingnoob** [sungyubkim/MINE-Mutual-Information-Neural-Estimation-#1]

**Comment by sungyubkim** [comment]
Oh thanks for productive question.
I've never try MINE to GAN or MNIST yet, but to my knowledge MINE was applied to Adversarially Learned Inference(ALI, https://arxiv.org/abs/1606.00704) and Information Bottleneck(https://arxiv.org/abs/1612.00410) in original MINE paper. I have no schedule to implement these immediately, but will implement these things in 1~2 month.
