### ISSUE TITLE
Awesome repo! Some questions about zero_gp and mi_obj?

### ISSUE THREAD

**Issue by shun-zheng** [sungyubkim/MINE-Mutual-Information-Neural-Estimation-#2]
Very appreciate for these awesome and intuitive demos for MINE!

I have one question:

1. As shown by [GAN_MINE.ipynb](https://github.com/sungyubkim/MINE-Mutual-Information-Neural-Estimation-/blob/master/GAN_MINE.ipynb), just setting zero_gp=True can prevent the GAN training from mode collapsing.

So, when zero_gp=True is added, is there any benefit of maximizing the mutual information by setting mi_obj=True?

I did not see any clear benefit by running the code, neither the final results nor the convergence speed. Do you have any insight on this behavior?

**Comment by sungyubkim** [comment]
Zero-centered gradient penalty was used for stability of adversarial learning.

Also, MINE can be used to stabilize the training of GAN. 

In this code, zeroGP is just an auxiliary regularization for GAN training.
